### ISSUE TITLE
Run-time segfault during execution of a simple kernel generated by GCC HSA back-end

### ISSUE THREAD

**Issue by marxin** [HSAFoundation/phsa-runtime#5]
Running switch-1.c (attached in the issue) triggers a segfault in runtime:

$ gcc -v
gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/home/marxin/Programming/bin/gcc2/lib/gcc/x86_64-pc-linux-gnu/6.0.0/lto-wrapper
Target: x86_64-pc-linux-gnu
Configured with: ../configure --prefix=/home/marxin/Programming/bin/gcc2 --disable-bootstrap --disable-libsanitizer --disable-multilib --with-hsa-runtime=/home/marxin/bin/phsa-runtime/ --enable-offload-targets=hsa
Thread model: posix
gcc version 6.0.0 20160310 (experimental) (GCC) 

$ gcc switch-1.c -fopenmp

HSA_DEBUG=1 ./a.out
HSA debug: HSA run-time initialized
HSA debug: There are 1 HSA GPU devices.
HSA debug: HSA agent initialized, queue has id 0
HSA debug: HSA agent initialized, kernel dispatch queue has id 1
HSA debug: Encountered 1 kernels in an image
HSA debug: Created a finalized program
HSA warning: Could not open a shared BRIG library: libhsamath.so
HSA warning: Could not open a shared BRIG library: libhsastd.so
HSA debug: Finalization done
PHSAProgram::symbolName called for: main__omp_fn_0
HSA debug: Froze HSA executable with the finalized code object
HSA debug: Located kernel &main__omp_fn_0
HSA debug: Kernel structure for &main__omp_fn_0 fully initialized with following segment sizes: 
HSA debug:   group_segment_size: 0
HSA debug:   private_segment_size: 4
HSA debug:   kernarg_segment_size: 8
HSA debug:   omp_data_size: 0
HSA debug:   gridified_kernel_p: 0
HSA debug: 
HSA debug: GOMP_OFFLOAD_run called with no launch attributes

Kernel has following dependencies:
  this: 0x18d04c0
  queue: 0x18c6bc0
  omp_data_memory: (nil)
  kernarg_address: 0x18d5560
  object: 26039440
  signal: 26019128
  private_segment_size: 4
  group_segment_size: 0
  children dispatches: 0
  omp_num_threads: 64

HSA debug: Got AQL index 0
HSA debug: Copying kernel runtime pointer to kernarg_address
HSA debug: Going to dispatch kernel &main__omp_fn_0
HSA debug: Kernel dispatched, waiting for completion
HSA debug: Released kernel dispatch: 0x18d04c0 has value: 0 ((nil))
foo: 0 = -1
foo: 1 = 11
foo: 2 = -1
Segmentation fault (core dumped)

The problem is somewhere in queue packet resolver:
Program received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7ffff5799700 (LWP 19193)]
0x00007ffff6f6b94a in CpuAgent::DoWork (this=0x61c520) at /home/marxin/Programming/phsa-runtime/core/runtime/cpu_agent.cpp:113
113                (gccbrigKernelLauncherFunc)kernSymb->address;
(gdb) bt
#0  0x00007ffff6f6b94a in CpuAgent::DoWork (this=0x61c520) at /home/marxin/Programming/phsa-runtime/core/runtime/cpu_agent.cpp:113
#1  0x00007ffff6f6b5d1 in CpuKernelExecutorThread (agent=0x61c520) at /home/marxin/Programming/phsa-runtime/core/runtime/cpu_agent.cpp:64
#2  0x00007ffff6f74c61 in boost::_bi::list1<boost::_bi::value<CpuAgent*> >::operator()<void (*)(CpuAgent*), boost::_bi::list0> (this=0x61d2d0, f=@0x61d2c8: 0x7ffff6f6b5b9 <CpuKernelExecutorThread(CpuAgent*)>, a=...) at /usr/include/boost/bind/bind.hpp:259
#3  0x00007ffff6f748f7 in boost::_bi::bind_t<void, void (*)(CpuAgent*), boost::_bi::list1<boost::_bi::value<CpuAgent*> > >::operator() (this=0x61d2c8) at /usr/include/boost/bind/bind.hpp:1222
#4  0x00007ffff6f74520 in boost::detail::thread_data<boost::_bi::bind_t<void, void (*)(CpuAgent*), boost::_bi::list1<boost::_bi::value<CpuAgent*> > > >::run (this=0x61d110) at /usr/include/boost/thread/detail/thread.hpp:116
#5  0x00007ffff60dce5d in ?? () from /usr/lib64/libboost_thread.so.1.60.0
#6  0x00007ffff79954a4 in start_thread () from /lib64/libpthread.so.0
#7  0x00007ffff76d2ded in clone () from /lib64/libc.so.6

where it tries to process a packet that actually wasn't filled up to a queue:

(gdb) list
108        
109              core::loader::KernelSymbol* kernSymb =
110                (core::loader::KernelSymbol*)kernel_packet->kernel_object;
111        
112              gccbrigKernelLauncherFunc kernelFunc =
113                (gccbrigKernelLauncherFunc)kernSymb->address;
114        
115              phsa::PHSAProgram& phsaProg =
116                *static_cast<phsa::PHSAProgram*>(kernSymb->Data());
117        
(gdb) p kernSymb
$1 = (core::loader::KernelSymbol *) 0x0

[archive.zip](https://github.com/HSAFoundation/phsa-runtime/files/167700/archive.zip)

**Comment by marxin** [comment]
Please apply following patch to force HSA plugin to consider also CPU agents.
